name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
    
    - name: Show folders
      run: find .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: SkinsRestorer
        path: ./Jar/target/SkinsRestorer.jar